### PR TITLE
Drop py27

### PR DESCRIPTION
**Pull request by terrycain**
Drops Python 2.7 and adds some basic type hints where its easy to do so.

Probably best off looking at the diff's between the individual commits.

Might want to look at running `isort` to sort the imports at some point in the future

### CODE REVIEW

**Comment by stevearc** [comment]
Looking good so far! Is this ready for merge or did you have more changes you wanted to make?

**Comment by terrycain** [comment]
Go ahead and merge, there is some more stuff I want to add but I'll do that in a separate pr when I have the energy :D, mainly just adding in more type hints, completely non-functional aesthetic stuff

**Comment by stevearc** [comment]
Created a 1.1 branch and merged this into that. Also added `mypy` to the tox config so we catch type errors in CI. I also made a branch where I added isorting, but I'm leaving that unmerged for now so it doesn't cause you any merge conflicts. Will merge it in to 1.1 after your PRs are all in.

**Comment by terrycain** [comment]
Nice I'll rebase my hash support pr onto 1.1, will probably finish that one before Monday.

**Comment by stevearc** [comment]
Don't know why this never closed, but it's all done and merged now

**Pull request closed without merging**
