### PR TITLE
fix json redirects

### PR DESCRIPTION
**Pull request by thehesiod**

### CODE REVIEW

**Comment by thehesiod** [comment]
given this is a totally new option and we maintain 100% backwards compatibility I don't think a minor revision is necessary anymore

**Comment by stevearc** [comment]
This is great! I like it so far, but there's a couple things that have to be done before I can merge it

* [ ] write a test for fallback_base_url
* [ ] fix failing tests
* [ ] fix the [other usages of fallback_url](https://github.com/stevearc/pypicloud/search?q=fallback_url&unscoped_q=fallback_url) to also accept fallback_base_url

I'm happy to help out with this. I'll start at the bottom of the list and work my way upwards, posting here with updates.

**Comment by stevearc** [comment]
Damn you're fast!

Okay, I threw up a commit in https://github.com/stevearc/pypicloud/commits/fallback_base_url that I think does the rest. I'm too tired to trust my code right now, so I'm going to look at it in the light of day and if it looks good I'll merge the PR and patch this on top of it

**Comment by stevearc** [comment]
Awesome! I've merged it into the [1.0](https://github.com/stevearc/pypicloud/commits/1.0) branch, and will cut a new release soon. Thanks for the PR!

**Comment by thehesiod** [comment]
thanks for this project!

**Pull request merged**
