### PR TITLE
Added tracking of package uploader

### PR DESCRIPTION
**Pull request by YannayH**
Added feature of tracking the user who uploaded a package in the database and in the cache.
The user is displayed as an additional column in the package page in the UI.

### CODE REVIEW

**Comment by stevearc** [comment]
Thanks for the PR! I don't have time to do a full review right now, but I'll get to it as soon as I'm able.

**Comment by stevearc** [comment]
Apologies, but I'm going off the grid for about a week and don't have time to do a proper review before then. This is still on my todo list, and once I get back I'll get to it as soon as possible

**Review by stevearc — CHANGES_REQUESTED** [review]
In general, I'm on board with this change. I think that the uploading user is a reasonable piece of metadata to add to the packages. Structurally, this PR is adding the uploader directly to the package model classes as a new field, but I'd prefer the approach of putting the uploader into the "metadata" dict on the package for two reasons:

1. Decreases surface area of the change. Requires fewer changes across all the different models, which makes it less likely that there's an edge case missed somewhere.
2. Doesn't change the schema of the backends. As-is, anyone using the SQL cache backend would have to perform a migration to add the new column.

If you have strong reasons for doing it this way instead of using the metadata dict, I could be persuaded.

**Comment by YannayH** [comment]
Closing for PR #312, using your suggested method there.

**Pull request closed without merging**
