### PR TITLE
fix json redirects

### PR DESCRIPTION
**Pull request by thehesiod**
fixes https://github.com/stevearc/pypicloud/issues/186

### CODE REVIEW

**Comment by thehesiod** [comment]
ugh, what a pain, /simple and /pypi are NOT interchangeable.

Examples
1) https://pypi.org/simple/fiona/json yields 404, whereas https://pypi.org/pypi/fiona/json returns the correct results.
2) https://pypi.org/simple/Fiona/ returns the simple results, whereas https://pypi.org/pypi/fiona/ redirects to https://pypi.org/project/Fiona/ and is the product page.

**Comment by stevearc** [comment]
Thanks for the PR!

Merging this patch as-is will change the behavior of `fallback_url`. If someone had a `fallback_url` with an empty path that was functioning as `/simple`, this will cause their links to be broken now. A couple ideas:

1. If the redirect is happening from a `/<package>/json` endpoint (i.e. `context.name == 'json'`), you could parse the fallback_url and if the last path component is `simple`, switch it to `pypi` then complete the redirect. This is a bit of a hack, but it fixes most people's configurations in-place and doesn't break anything that's currently working, as it'll only affect the `/json` redirects.
or
2. Deprecate `fallback_url` and replace it with a new option, like `redirect_url_base`. Probably also add `redirect_url_simple` and `redirect_url_pypi` in case someone needs to specify a redirect url without `/simple` or `/pypi` in it.

I'm open to other ideas as well, those were just the first two that came to mind.

**Comment by thehesiod** [comment]
ok, thinking about this more:

so pypicloud is support to be re-directing to another pypi server.  The official pypi server is http://pypi.python.org/ (hereby PPYPI)  so all pypi servers should obey to PPYPI's implementation.  The current default pypicloud implementation does not so it needs to be fixed.  pypicloud potentially supports redirecting to non-PYPI prefixed pypi servers so it needs to support that as well.

Given this, and the fact that making it support broken backwards compatibility is pretty ugly, I think the current implementation is almost ok if the major or minor rev is bumped (to signify there's a potential breaking change) and the change in behavior is described as:

1) to forward to a server that behaves like PPYPI server do not specify a path on `fallback_url `. 
2) any path on the `fallback_url` will be treated as a prefix when redirected.

if this is accepted, then I'd change the default to not have a prefix.  If this isn't accepted, and backwards compatibility is paramount then ya I'd introduce yet another configuration var :)

but realistically I think the cleanest is slightly changing the behavior...that's why there's semantic versioning :)

thoughts?

**Comment by stevearc** [comment]
I'm 90% on board with your proposal (it will require a minor version bump), but I do want to keep compatibility with old configs. As long as `fallback_url` continues to behave as expected, I'm fine with changing the expectations and moving to a new config var.

**Comment by thehesiod** [comment]
k, I'll create a new PR soon with the changes as I have some prod builds which points to this branch.

**Comment by thehesiod** [comment]
superseded by https://github.com/stevearc/pypicloud/pull/188 per convo

**Pull request closed without merging**
