### PR TITLE
Support for Google Cloud Storage backend

### PR DESCRIPTION
**Pull request by mchalek**
hi @stevearc ,

thanks for your wonderful pypicloud package.  We have been using it with the `FileStorage` backend for nearly 7 months at Etsy and it has been flawless in that time.

One feature that we have been longing for is support for a Google Cloud Storage backend, and we finally decided to go for it and implement it.

We have been aware of #81 but it seemed as if development on that branch has stalled.  Rather than trying to pick up where that left off, we decided to start fresh but to keep in mind your recommendations in response to that PR.

Specifically, our changes include:
1. To avoid code duplication, factor common logic out of the `S3Storage` class into an abstract `ObjectStoreStorage` class that can be used as the base for both the S3 and GCS backends
2. No custom packages needed, as we are using the Google Cloud Python library for our GCS requests.  We added this library as an install extra, so that it will not be installed on existing S3 installations unless opted-in.
3. Add unit tests --- we matched the unit testing functionality one-for-one with the existing tests for `S3Storage`.

We have some more testing to do, and some more cleanup and documentation to add, but we wanted to submit this now so that you could potentially look at it and provide feedback on what we have so far.  The tests all pass and we have confirmed that the server and migration scripts both seem to work properly.

There are a few remaining GCS-specific "gotchas" that we may also have to consider, either now or in a future PR.  For example:
1. the GoogleCloudStorage python library cannot sign URLs when running on Google Compute Engine, without using a workaround described here: https://github.com/GoogleCloudPlatform/                      google-auth-library-python/issues/50.  Our testing has all been done using service-account private keys in order to avoid this issue.
2. We have not investigated the behavior of GCS with buckets containing periods in their names
3. We have not implemented the `public_url` functionality that the S3Storage backend provides
4. We have not included support for customized server-side encryption on GCS

### CODE REVIEW

**Comment by stevearc** [comment]
This looks great! I'm GCS support is something that's been requested numerous times, but I haven't had the time or expertise with the platform to do it myself. I'm sure a lot of people will be thrilled about this!

I'll start reviewing now, but it'll take a couple days since I want to get a GCS account myself and poke it to see how it works. Thanks for the PR!

**Comment by mchalek** [comment]
hi @stevearc my pleasure!  Thanks for the quick response.

Until I have a chance to write real docs, I just wanted to let you know how the GCS authentication currently works, so that you can test yourself with your own GCS.

Because of the issue I noted regarding GCE, you have to run this using a service account credentials file.  You can create a GCP service account with the `storage.admin` role, and then download a JSON key file for it.  Then, you would add a pointer to that file to your runtime environment, via something like:

```
$ GOOGLE_APPLICATION_CREDENTIALS=/path/to/my/key.json pserve config.ini
```

The GCS client library will read that environment var and extract the credentials appropriately.

I will be working on this further this week, perhaps investigating the workaround in google's docs to allow us to skip the key file step and use the instance credentials when the server is installed on GCE.

Please let me know if you have any questions or concerns!

**Comment by mchalek** [comment]
Hi @stevearc , sounds great!  I'll work on addressing those points and I'll let you know once it's done.  Shouldn't be more than a couple of days.

**Comment by stevearc** [comment]
Hey @mchalek! Any progress?

**Comment by mchalek** [comment]
oh hey @stevearc sorry i have been a little swamped over here.  Let me see if I can address all your comments right now and push an update.  I won't have time to write docs today but it sounded like you would be okay with merging this and then writing docs in a follow-on commit?

**Comment by stevearc** [comment]
No worries! I know how that happens. I'm in no rush, so don't feel like you have to hurry.

I have a weak preference for merging this with the docs, but if you'd like to go ahead and get these changes in I'm fine with following up on the docs later.

**Comment by mchalek** [comment]
Oh I just saw your comment re: your preference for merging this with docs.  No problem.  Actually maybe better to hold off on merging this, as it will apply more pressure to me to finally sit down and write those docs!

**Comment by mchalek** [comment]
hey @stevearc I pushed some docs today.  let me know what you think.  I also had to work out some merge conflicts.  I think I got them right, but I'm waiting on the tests to confirm.

**Comment by stevearc** [comment]
Looks good to me! Thanks for all your work!

**Comment by mchalek** [comment]
No problem @stevearc !  Please let me know if you need anything more from me for this.

**Pull request merged**
