### PR TITLE
Add PEP-503 data-requires-python attribute

### PR DESCRIPTION
**Pull request by ikonst**
Store the metadata value provided by twine etc. and return it in the simple package list.

### CODE REVIEW

**Comment by ikonst** [comment]
ptal @stevearc

I've tested it with twine, which provides the entire metadata dictionary in the input JSON:
https://github.com/pypa/twine/blob/efd0e4402c9f14c3b2ad3359c861a3112b8c6b36/twine/repository.py#L139-L146

**Comment by stevearc** [comment]
Thanks for the PR!

First, for my own benefit let me lay out the required pieces of getting full support for `data-requires-python`:

1. Accept the metadata in uploads
1. Fetch the metadata from pypi
1. Store the metadata in the cache
1. Store the metadata in storage
1. Serve the metadata from the /simple endpoint
1. Serve the metadata from the /json endpoint

It looks like this PR is adding support for 1, 3, and 5. Which is great! I'm fine with accepting PRs that make partial progress as long as they don't add anything that will need to be removed later. All of these changes look good.

You mention that you tested it with twine. Could you give me some more concrete steps so I can reproduce it?

Lastly, there are a couple tests failing and a few files in need of black formatting. Unfortunately it seems like travis-ci has disconnected from this repo, so I'll have to go debug that. In the meantime, `tox` should run all tests and linters.

**Comment by ikonst** [comment]
> It looks like this PR is adding support for 1, 3, and 5. Which is great! I'm fine with accepting PRs that make partial progress as long as they don't add anything that will need to be removed later. All of these changes look good.

You're right. I've intentionally didn't try to add it to the JSON endpoint, not only to keep the change set smaller, but also since the purpose wasn't clear to me.

To clarify what I mean, twine sends more metadata than just `requires_python`. I've added handling only for `requires_python` since it serves the immediate goal of skipping incompatible packages during version matching (for internal packages).

If we want the JSON endpoint to be comprehensive (for no particular reason or feature in mind), perhaps we should store all of the metadata and serve it back through the JSON endpoint.

> 4. Store the metadata in storage

To clarify, the S3 is storage and DynamoDB is cache, meaning that the DynamoDB table can expect to be flushed and re-populated from storage? It's tricky since metadata is served to me on a silver platter by twine, but if I need to get it from storage, it means I need to unpack the tarballs and extract the metadata? Is there code for this in pypicloud already?

> You mention that you tested it with twine. Could you give me some more concrete steps so I can reproduce it?

```console
$ cd pypicloud
$ . venv/bin/activate
$ python setup bdist
$ pip install twine
$ twine upload --repository-url http://localhost:6543/ -u USERNAME -p PASSWORD dist/pypicloud-1.0.13.macosx-10.14-x86_64.tar.gz
```

(This test actually made me find a bug -- twine sends an empty string for parameters not defined in your package manifest, which DynamoDB cannot store.)

Generally, the payload sent by twine looks something like this:
```json
{
    "comment": "",
    "requires_python": "",
    "maintainer": "",
    "description": "PyPI Cloud\n==========\n: <... rest of the readme ...>",
    "metadata_version": "2.1",
    "description_content_type": "",
    "md5_digest": "ec162f3635c7f8f2e262403246bd75c4",
    "filetype": "sdist",
    ":action": "file_upload",
    "maintainer_email": "",
    "platform": "any",
    "keywords": "pypi s3 cheeseshop package",
    "blake2_256_digest": "",
    "classifiers": "Topic :: System :: Systems Administration",
    "sha256_digest": "e12c505f486aa36e05191b3389db4c4a10b84a56bf94bb0ba77b4e2a89a4990f",
    "download_url": "",
    "name": "pypicloud",
    "license": "MIT",
    "author": "Steven Arcangeli",
    "home_page": "http://pypicloud.readthedocs.org/",
    "pyversion": "",
    "summary": "Private PyPI backed by S3",
    "author_email": "stevearc@stevearc.com",
    "version": "1.0.13",
    "protocol_version": "1",
    "provides_extras": "doc"
}
```

> Lastly, there are a couple tests failing and a few files in need of black formatting. Unfortunately it seems like travis-ci has disconnected from this repo, so I'll have to go debug that. In the meantime, `tox` should run all tests and linters.

Good luck with travis-ci. I ran some of the tests through `setup.py nosetests` -- I'll give tox a whirr again.

**Comment by stevearc** [comment]
Yeah, the JSON endpoint isn't critical to the functionality. I added it because it was easy and I thought people might want it if they're building tools to interact with the server.

> To clarify, the S3 is storage and DynamoDB is cache, meaning that the DynamoDB table can expect to be flushed and re-populated from storage?

Yes. As it is, when you upload a package it will contain the `requires_python` metadata until the cache gets flushed or reset for some reason. This part isn't too tricky; I outlined the places that would have to be updated in https://github.com/stevearc/pypicloud/issues/219#issuecomment-607624542. The trickier part is to fetch the `requires_python` metadata from upstream.

These changes look good though!

**Comment by stevearc** [comment]
Merged into the 1.0 branch. Will close when next release goes out

**Comment by ikonst** [comment]
Thanks!

**Pull request merged**
